version: "3"
services:
  updater:
    build: .
    environment:
      - SOLR_URL=http://solr:8983/solr
    volumes:
      - ".:/opt/updater"
    depends_on:
      - solr

  solr:
    image: solr:8.5
    ports:
      - "8982:8983"
    environment:
      - ZK_HOST=zookeeper:2181
    volumes:
      - solr-data:/var/solr
      - ./data/solr/authoritydata:/opt/solr/server/solr/configsets/authoritydata
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.6
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:288:388;2181

volumes:
  solr-data:
