version: '3.4'
services:
  updater:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./.env
    volumes:
      - '.:/opt/authoritydata_udpater'
